version: "3.8"

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pca-dashboard
    ports:
      - "8050:8050"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
