# In file: .github/workflows/ci.yml

# Name of the workflow, which will appear in the "Actions" tab on GitHub
name: Python Application CI

# --- Triggers ---
# This workflow runs on pushes and pull requests to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# --- Jobs ---
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" job
  build:
    # The type of virtual machine to run the job on
    runs-on: ubuntu-latest

    # A sequence of tasks that will be executed as part of the job
    steps:
      # 1. Check out your repository code so the job can access it
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up a specific version of Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install all dependencies from your requirements.txt file
      # This now includes pytest, duckdb, etc.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Run your tests using pytest
      # This is the command that determines if the build passes or fails
      - name: Run PyTest suite
        run: |
          python -m pytest

